nodeLinker: node-modules

# yarnPath: .yarn/releases/yarn-3.6.4.cjs

npmAuthToken: ${NODE_AUTH_TOKEN}
npmAlwaysAuth: true
# npmRegistryServer: https://npm.pkg.github.com # URL for private registry